version: '3.3'

networks:
  bee_net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/16

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ${PWD}/dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test123
    networks:
     bee_net:
      ipv4_address: 10.10.0.3

  spring-boot:
    build: .
    depends_on:
        - db
    ports:
      - 8080:8080
    networks:
     bee_net:
      ipv4_address: 10.10.0.2